sudo: required
language: cpp
compiler: c
dist: xenial
notifications:
  email: false

before_install:
    - git submodule init
    - git submodule update --recursive

script:
    - mkdir build
    - cd build 
    - cmake -DBUILD_DAP_UDP_SERVER_TESTS=ON ../
    - make
    - ctest --verbose

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libev-dev

