sudo: required
language: cpp
compiler: gcc
dist: trusty
notifications:
  email: false

before_install:
    - git submodule init
    - git submodule update --recursive

script:
    - export CC=gcc-5
    - mkdir build
    - cd build 
    - cmake -DBUILD_DAP_TESTS=ON ../
    - make
    - ctest --verbose

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5

